name: Build Web
run-name: ${{ github.actor }} is building for web ğŸš€
on: [push]
jobs:
  Build-Web:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
          channel: 'stable'
      - run: flutter --version
      
      - run: flutter pub get
      # this fails... (smoke test)
      #- run: flutter test
      - run: flutter build web --web-renderer html
      
      # commit the build files to the repo (https://joht.github.io/johtizen/build/2022/01/20/github-actions-push-into-repository.html#github-events)
      - uses: stefanzweifel/git-auto-commit-action@v4

      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
